development:
  adapter: mysql
  encoding: utf8
  database: pin-share-development
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: pin-share-test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: pin-share
  username: root
  password: root
  pool: 5
  timeout: 5000